###############################################################################
# RESOURCE TYPES                                                              #
###############################################################################
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: ghcr.io/typositoire/concourse-helm3-resource

  - name: k8s
    type: registry-image
    source:
      repository: jgriff/k8s-resource

###############################################################################
# RESOURCES                                                                   #
###############################################################################
resources:
  #
  # Repository containing the override value file for nfs
  #
  - name: rws-infra-nfs
    type: git
    icon: bitbucket
    source:
      uri: ((CVS.K8S.NFS.REPO_URI))
      branch: ((CVS.K8S.NFS.REPO_BRANCH))
      username: ((CVS.AUTH.USERNAME))
      password: ((CVS.AUTH.PASSWORD))

  #
  # Repository containing helm chart
  # https://github.com/Typositoire/concourse-helm3-resource#source-configuration
  #
  # - name: helm-resources
  #   type: helm
  #   icon: helm
  #   source:
  #     cluster_url: ((KUBERNETES.CLUSTER_URL))
  #     token: ((KUBERNETES.OIDC_TOKEN))
  #     insecure_cluster: true
  #     # tracing_enabled: true
  #     repos:
  #       - name: helm-repo
  #         url: https://besartsulejmani.github.io/rws-k8s-helm/

  #
  # Kubernetes cluster to deploy resources to
  # https://github.com/jgriff/k8s-resource#source-configuration
  #
  - name: k8s-cluster-resources
    type: k8s
    icon: kubernetes
    source:
      url: ((KUBERNETES.CLUSTER_URL))
      token: ((KUBERNETES.OIDC_TOKEN))
      namespace: ((KUBERNETES.NAMESPACE.NFS))
      insecure_skip_tls_verify: true
      timeout: 5m
      resource_types: deployment,service,pod

###############################################################################
# JOBS                                                                        #
###############################################################################
jobs:
  - name: install-nfs-data-import
    plan:
      # Get nfs helm configuration and additional K8s resources
      - get: rws-infra-nfs
      # # Put K8s resources
      - put: k8s-cluster-resources
        inputs: all
        params:
          kubectl: |
            apply
            -f rws-infra-nfs/seed/k8s/
          namespace: ((KUBERNETES.NAMESPACE.NFS))
      # - put: helm-resources
      #   inputs: all
      #   params:
      #     chart: helm-repo/nfs-seed
      #     version: 0.4.0
      #     release: nfs-seed
      #     create_namespace: true
      #     # values: helm-repo/nfs-seed/values.yaml
      #     namespace: nfs